name: Calling dotnet Pipeline module.

on:
  push:
    branches:
      - main

jobs:
  call-task-pipeline:
    uses: nadeemali5/Called_Workflow_Module/.github/workflows/dotnet.yml@main  # Reusable workflow call
    with:
      branch_or_tag: ${{ github.ref_name }}
