name: .NET 6 Build, Restore, and Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up .NET 6 SDK
      - name: Set up .NET 6 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'  # Ensure .NET 6 is used

      # Step 3: Ensure .NET 6 is used with a global.json (if not already present in the repo)
      - name: Create global.json if not exists
        run: |
          if (-not (Test-Path 'global.json')) {
            Write-Host "Creating global.json to specify .NET 6 SDK"
            echo '{
              "sdk": {
                "version": "6.0.0"
              }
            }' > global.json
          }

      # Step 4: Restore dependencies with specified parameters
      - name: Restore dependencies
        run: |
          dotnet restore /p:zipAfterPublish=true \
                          /p:modifyOutputPath=true \
                          /p:selectOrConfig=config \
                          /p:feedRestore="" \
                          /p:includeNuGetOrg=true

      # Step 5: Build the application
      - name: Build application
        run: dotnet build --configuration Release

      # Step 6: Run the application
      - name: Run application
        run: |
          dotnet run --configuration Release
