name: Calling nodejs Pipeline module.

on:
  push:
    branches:
      - main

jobs:
  call-task-pipeline:
    uses: nadeemali5/Called_Workflow_Module/.github/workflows/nodejs.yml@main  # Reusable workflow call
    with:
      branch_or_tag: ${{ github.ref_name }}
      verbose: true 
      customCommand: install
      customRegistry: useNpmrc
      customFeed: ""
      customEndpoint: ""
      publishRegistry: useExternalRegistry
      publishFeed: ""
      publishPackageMetadata: true
      publishEndpoint: ""
